name: create an image and push to Docker_hub

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag alone_maven_app:latest
      - name: Run the container
        run: docker run -itd --name alone_maven_app -p 80:3333 alone_maven_app:latest
      - name: Test the container
        run: | 
          sleep 5
          output=$(docker logs alone_maven_app 2>&1)
          echo "$output"
          if [[ "$output" == *"Hello, world!"* ]]; then
            echo "Test passed: Hello, world! found in the container logs."
          else
            echo "Test failed: Hello, world! not found in the container logs."
            exit 1
          fi
        shell: bash
      - name: Change image name
        run: docker tag alone_maven_app:latest ddriham/alone_maven_app:latest
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker push 
        run: docker push ddriham/alone_maven_app:latest
